# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c24e58a5c830c7a3eda14ae5d6f8f6da"
name = "basket-booster-discounts"
application_url = "https://app.basketbooster.ca"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://app.basketbooster.ca/auth/callback" ]
