// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/webhooks": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/terms": {
    params: {};
  };
  "/app": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/webhooks" | "/privacy" | "/support" | "/auth/*" | "/terms" | "/app" | "/app/additional";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/webhooks.tsx": {
    id: "routes/webhooks";
    page: "/webhooks";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/support.tsx": {
    id: "routes/support";
    page: "/support";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/additional";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/webhooks": typeof import("./app/routes/webhooks.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/support": typeof import("./app/routes/support.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
};